version: 3

tasks:
  apps:
    cmds:
      - docker-compose -f docker-compose-applications.yml up

  idp:
    cmds:
      - docker-compose -f docker-compose-idp.yml up

  other:
    cmds:
      - docker-compose up