version: 3

tasks:
  backends:
    cmds:
      - docker-compose -f docker-compose-external-backend.yml -f docker-compose-internal-backend.yml up

  internal-backend:
    cmds:
      - docker-compose -f docker-compose-internal-backend.yml up

  external-backend:
    cmds:
      - docker-compose -f docker-compose-external-backend.yml up

  idp:
    cmds:
      - docker-compose -f docker-compose-identity-provider.yml up

  other:
    cmds:
      - docker-compose up

  all:
    cmds:
      - task other
      - task idp
      - task backends