name: go-backend-ci
run-name: CI for go-backend project
on:
  push:
    branches:
      - 'main'

jobs:
  go-backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - name: Set up go
        uses: actions/setup-go@49bc3307c5d359429e8aee983859eb8dfad28c6b
        with:
          go-version: '^1.20.3'

      - name: Run tests
        run: |
          go test -v ./...
